### ISSUE TITLE
Error resuming survey Could not find the route "ResumeSurveyIntent" in your handler function.

### ISSUE THREAD

**Issue by robertavram-md** [robertavram-md/alexa-hf#12]
Using the new back end I am getting this error when trying to resume a survey:
Could not find the route "ResumeSurveyIntent" in your handler function.

**HOW**
1. Restart skill with survey paused
2. Say 'start a new one'
3. Say 'proceed' -> it will give this error

`error
Error: Could not find the route "ResumeSurveyIntent" in your handler function.
    at Promise (/Users/papirobbi/Documents/GitHub/alexa-hf/node_modules/jovo-framework/lib/handler.js:43:21)
    at new Promise (<anonymous>)
    at Handler.handle (/Users/papirobbi/Documents/GitHub/alexa-hf/node_modules/jovo-framework/lib/handler.js:26:16)
    at loadUserDataOnRequest.then.then.then.then.then.then (/Users/papirobbi/Documents/GitHub/alexa-hf/node_modules/jovo-framework/lib/jovo.js:185:43)
Local server did not return a valid JSON response:`

**Comment by robertavram-md** [comment]
This is still occuring as of now.

**Comment by robertavram-md** [comment]
<img width="397" alt="screen shot 2018-09-27 at 12 56 00 pm" src="https://user-images.githubusercontent.com/8838962/46162082-488cdd00-c255-11e8-97b0-da77dd1558f3.png">

**Comment by ghost** [comment]
@robertavram-md  usesr need to say "proceed to questions", please, try again.

**Comment by ghost** [comment]
@robertavram-md we added alias "proceed"
